[[mgr.prepend_keymap]]
on   = [ "m" ]
run  = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on   = [ "'" ]
run  = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on   = [ "b", "d" ]
run  = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on   = [ "J" ]
# 修改点：将 "$SHELL" 改为 "pwsh"，确保在 Windows 下按下 J 能正常呼出终端
run  = 'shell "pwsh" --block'
desc = "Open interactive shell here"
